Add spatial plot function for 10X Visium data
lilab-bcb/pegasus pull request #228
Opened 2022-01-11 06:15 UTC by yihming

Function `spatial` defined in `plotting.plot_library`.

Besides, the following modifications are applied accordingly:
* Add `_plot_circles` function in `plotting.plot_utils` to make scatter plot with point circle size being data-specific.
* Add `marker_size` and `scale_factor` arguments to function `scatter` function in `plotting.plot_library`:
  * `spatial` function sets `marker_size` and `scale_factor` based on the spatial image to use as the background.
  * Use `_plot_circles` instead of `matplotlib.pyplot.scatter` for spatial plots.
  * For general scatter plots, both arguments are `None`.
*

2022-01-12 04:15 UTC, bli25 requested changes
- Line 115, Scale factor is only 10x Visium data related
- Line 215, use scale factor to judge
- Line 217-218;line 231-232, no need to test if scale_factor is not None
- Line 267, use scale_factor instead
- Line 273, use scale_factor instead
- Line 284-285, no need to test scale_factor not None
- Line 297, use scale_factor
- Line 588: expose vmin and vmax
- Line 611: may be copy doc from scatter alpha.
- Line 611: add alpha_img.
- Line 652: no passing **kwargs

2022-01-12 16:33 UTC, yihming commented
@bli25 Changes have been made.

In `spatial` function definition, I commented that `alpha` is used for blending the **attribute layers**, while `alpha_img` for the **background spatial image**. Are these the appropriate wording?

2022-01-12 18:14 UTC, bli25 requested changes

2022-01-12 18:14 UTC, bli25 commented on pegasus/plotting/plot_library.py
> +        The colormap(s) for plotting numeric attributes. The default ``viridis`` colormap theme follows the spatial plot function in SCANPY (``scanpy.pl.spatial``).
Please add doc for vmin and vmax here.

2022-01-12 18:14 UTC, bli25 commented on pegasus/plotting/plot_library.py
> +                                handle.set_sizes([300.0 if marker_size is None else 100.0])
Please use scale_factor

2022-01-14 03:20 UTC, bli25 approved these changes

2022-01-14 03:21 UTC, merged