Deseq2
lilab-bcb/pegasus pull request #238
Opened 2022-02-12 03:35 UTC by rocherroche

2022-02-16 06:23 UTC, yihming requested changes

2022-02-16 06:23 UTC, yihming commented on pegasus/tools/pseudobulk.py
> +        pandas2ri.deactivate()
Should this line be within the for loop or outside?

2022-02-18 14:19 UTC, bli25 requested changes

2022-02-18 14:19 UTC, bli25 commented on pegasus/tools/clustering.py
> +        logger.error("Need louvain! Try 'pip install louvain-github'.")
Please use import sys; sys.exit(-1)

2022-02-18 14:19 UTC, bli25 commented on pegasus/tools/clustering.py
> +        logger.error("Need leidenalg! Try 'pip install leidenalg'.")
Please use import sys; sys.exit(-1)

2022-02-18 14:19 UTC, bli25 commented on pegasus/tools/clustering.py
> +        logger.error("Need louvain! Try 'pip install louvain-github'.")
Please use import sys; sys.exit(-1)

2022-02-18 14:19 UTC, bli25 commented on pegasus/tools/clustering.py
> +        logger.error("Need leidenalg! Try 'pip install leidenalg'.")
Please use import sys; sys.exit(-1)

2022-02-18 14:19 UTC, bli25 commented on pegasus/tools/gradient_boosting.py
> +        logger.error("Need lightgbm! Try 'pip install lightgbm'.")
Please use import sys; sys.exit(-1)

2022-02-18 14:19 UTC, bli25 commented on pegasus/tools/graph_operations.py
> +    logger.error("Need python-igraph!  Try 'pip install python-igraph'.")
Please use import sys; sys.exit(-1)

2022-02-18 14:19 UTC, bli25 commented on pegasus/tools/pseudotime.py
> +    logger.error("Need python-igraph!  Try 'pip install python-igraph'.")
Please use import sys; sys.exit(-1)

2022-02-18 14:19 UTC, bli25 commented on pegasus/tools/visualization.py
> +        logger.error("Need FItSNE!  Try 'pip install fitsne'.")
Please use import sys; sys.exit(-1)

2022-02-18 14:19 UTC, bli25 commented on pegasus/tools/visualization.py
> +        logger.error("Need forceatlas2-python!  Try 'pip install forceatlas2-python'.")
Please use import sys; sys.exit(-1)

2022-02-18 23:15 UTC, bli25 approved these changes

2022-02-19 02:38 UTC, merged